# Generated by Django 4.2.16 on 2025-07-03 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('InProgress', 'InProgress'), ('Completed', 'completed')], default='Pending', max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=25)),
                ('dropdown', models.CharField(max_length=25)),
                ('vehicle_type', models.CharField(choices=[('Bus', 'bus'), ('Bike', 'bike'), ('Van', 'van'), ('Car', 'car')], max_length=10)),
                ('vehicle_no', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=None)),
                ('booked_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('upi', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('licence', models.FileField(blank=True, default=None, null=True, upload_to='licences/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('group', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lng', models.FloatField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='app.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('Bus', 'bus'), ('Bike', 'bike'), ('Van', 'van'), ('Car', 'car')], max_length=10)),
                ('vehicle_no', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacancy', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('source_lat', models.FloatField(default=None)),
                ('source_lon', models.FloatField(default=None)),
                ('dest_lat', models.FloatField(default=None)),
                ('dest_lon', models.FloatField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('vehicle_no', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_histories', to='app.user')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_histories', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app.user'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='app.user'),
        ),
    ]
