# Generated by Django 4.2.16 on 2025-07-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
